### ISSUE TITLE
TypeError: '>=' not supported between instances of 'PSKeyword' and 'float'

### ISSUE THREAD

**Issue by antoinejdd** [0xabu/pdfannots#58]
Hi,

For one of the pdf file I want to process, I get the following error : 

```py
Traceback (most recent call last):
  File "/home/antoinejdd/Documents/Projects/pdfannots/./pdfannots.py", line 8, in <module>
    pdfannots.cli.main()
  File "/home/antoinejdd/Documents/Projects/pdfannots/pdfannots/cli.py", line 141, in main
    doc = process_file(
  File "/home/antoinejdd/Documents/Projects/pdfannots/pdfannots/__init__.py", line 401, in process_file
    interpreter.process_page(pdfpage)
  File "/usr/local/lib/python3.9/dist-packages/pdfminer.six-20220524-py3.9.egg/pdfminer/pdfinterp.py", line 992, in process_page
    self.device.end_page(page)
  File "/usr/local/lib/python3.9/dist-packages/pdfminer.six-20220524-py3.9.egg/pdfminer/converter.py", line 80, in end_page
    self.receive_layout(self.cur_item)
  File "/home/antoinejdd/Documents/Projects/pdfannots/pdfannots/__init__.py", line 195, in receive_layout
    self.render(ltpage)
  File "/home/antoinejdd/Documents/Projects/pdfannots/pdfannots/__init__.py", line 295, in render
    self.render(child)
  File "/home/antoinejdd/Documents/Projects/pdfannots/pdfannots/__init__.py", line 290, in render
    self.update_pageseq(item)
  File "/home/antoinejdd/Documents/Projects/pdfannots/pdfannots/__init__.py", line 210, in update_pageseq
    x.update_pageseq(component, self.compseq)
  File "/home/antoinejdd/Documents/Projects/pdfannots/pdfannots/types.py", line 246, in update_pageseq
    self.pos.update_pageseq(component, pageseq)
  File "/home/antoinejdd/Documents/Projects/pdfannots/pdfannots/types.py", line 218, in update_pageseq
    if self.item_hit(component):
  File "/home/antoinejdd/Documents/Projects/pdfannots/pdfannots/types.py", line 210, in item_hit
    return (self.x >= item.x0
TypeError: '>=' not supported between instances of 'PSKeyword' and 'float'
```

This issue seems similar to #54

I can't publicly share the faulty pdf file, but I can send it to you in PM.

**Comment by 0xabu** [comment]
Hmm, `PSKeyword` sounds like a different bug. Can you [email me](mailto:ab@ab.id.au) the PDF (or a link to it)?

**Comment by 0xabu** [comment]
This should be fixed by the above-referenced commit. The PDF file does seem to have screwy outlines/bookmarks, so there are a bunch of warnings, but you get annotations output now. Thanks for the report!

**Comment by antoinejdd** [comment]
Thank you ! Like you said, this is fixed.
